Bank.o: Bank.cpp Bank.h FunctionUnit.h Mat.h SubArray.h RowDecoder.h \
 OutputDriver.h constant.h typedef.h Precharger.h SenseAmp.h Mux.h \
 PredecodeBlock.h BasicDecoder.h Comparator.h
BankWithHtree.o: BankWithHtree.cpp BankWithHtree.h Bank.h FunctionUnit.h \
 Mat.h SubArray.h RowDecoder.h OutputDriver.h constant.h typedef.h \
 Precharger.h SenseAmp.h Mux.h PredecodeBlock.h BasicDecoder.h \
 Comparator.h formula.h Technology.h global.h InputParameter.h MemCell.h \
 Wire.h
BankWithoutHtree.o: BankWithoutHtree.cpp BankWithoutHtree.h Bank.h \
 FunctionUnit.h Mat.h SubArray.h RowDecoder.h OutputDriver.h constant.h \
 typedef.h Precharger.h SenseAmp.h Mux.h PredecodeBlock.h BasicDecoder.h \
 Comparator.h formula.h Technology.h global.h InputParameter.h MemCell.h \
 Wire.h
BasicDecoder.o: BasicDecoder.cpp BasicDecoder.h FunctionUnit.h \
 OutputDriver.h constant.h typedef.h formula.h Technology.h global.h \
 InputParameter.h MemCell.h Wire.h SenseAmp.h
Comparator.o: Comparator.cpp Comparator.h FunctionUnit.h constant.h \
 global.h InputParameter.h typedef.h Technology.h MemCell.h Wire.h \
 SenseAmp.h formula.h
FunctionUnit.o: FunctionUnit.cpp FunctionUnit.h
InputParameter.o: InputParameter.cpp InputParameter.h typedef.h global.h \
 Technology.h MemCell.h Wire.h SenseAmp.h FunctionUnit.h constant.h
Mat.o: Mat.cpp Mat.h FunctionUnit.h SubArray.h RowDecoder.h \
 OutputDriver.h constant.h typedef.h Precharger.h SenseAmp.h Mux.h \
 PredecodeBlock.h BasicDecoder.h Comparator.h formula.h Technology.h \
 global.h InputParameter.h MemCell.h Wire.h
MemCell.o: MemCell.cpp MemCell.h typedef.h formula.h Technology.h \
 constant.h global.h InputParameter.h Wire.h SenseAmp.h FunctionUnit.h \
 macros.h
Mux.o: Mux.cpp Mux.h FunctionUnit.h constant.h global.h InputParameter.h \
 typedef.h Technology.h MemCell.h Wire.h SenseAmp.h formula.h
OutputDriver.o: OutputDriver.cpp OutputDriver.h FunctionUnit.h constant.h \
 typedef.h global.h InputParameter.h Technology.h MemCell.h Wire.h \
 SenseAmp.h formula.h
Precharger.o: Precharger.cpp Precharger.h FunctionUnit.h OutputDriver.h \
 constant.h typedef.h formula.h Technology.h global.h InputParameter.h \
 MemCell.h Wire.h SenseAmp.h
PredecodeBlock.o: PredecodeBlock.cpp PredecodeBlock.h FunctionUnit.h \
 RowDecoder.h OutputDriver.h constant.h typedef.h BasicDecoder.h \
 formula.h Technology.h global.h InputParameter.h MemCell.h Wire.h \
 SenseAmp.h
Result.o: Result.cpp Result.h BankWithHtree.h Bank.h FunctionUnit.h Mat.h \
 SubArray.h RowDecoder.h OutputDriver.h constant.h typedef.h Precharger.h \
 SenseAmp.h Mux.h PredecodeBlock.h BasicDecoder.h Comparator.h \
 BankWithoutHtree.h Wire.h global.h InputParameter.h Technology.h \
 MemCell.h formula.h macros.h
RowDecoder.o: RowDecoder.cpp RowDecoder.h FunctionUnit.h OutputDriver.h \
 constant.h typedef.h formula.h Technology.h global.h InputParameter.h \
 MemCell.h Wire.h SenseAmp.h
SenseAmp.o: SenseAmp.cpp SenseAmp.h FunctionUnit.h formula.h Technology.h \
 typedef.h constant.h global.h InputParameter.h MemCell.h Wire.h
SubArray.o: SubArray.cpp SubArray.h FunctionUnit.h RowDecoder.h \
 OutputDriver.h constant.h typedef.h Precharger.h SenseAmp.h Mux.h \
 formula.h Technology.h global.h InputParameter.h MemCell.h Wire.h
Technology.o: Technology.cpp Technology.h typedef.h
Wire.o: Wire.cpp Wire.h typedef.h SenseAmp.h FunctionUnit.h global.h \
 InputParameter.h Technology.h MemCell.h formula.h constant.h
formula.o: formula.cpp formula.h Technology.h typedef.h constant.h
main.o: main.cpp InputParameter.h typedef.h MemCell.h RowDecoder.h \
 FunctionUnit.h OutputDriver.h constant.h Precharger.h SenseAmp.h \
 Technology.h BasicDecoder.h PredecodeBlock.h SubArray.h Mux.h Mat.h \
 Comparator.h BankWithHtree.h Bank.h BankWithoutHtree.h Wire.h Result.h \
 formula.h macros.h
