#!/usr/bin/env python3
"""
MBMM Pipeline - Data Processing Stage
Process raw simulation metrics and output pre-calculated intermediate data

This module:
- Parses all stats_*.out files from /results/system/
- Performs centralized metric calculations (EDP, power splits, area density)
- Outputs pre-calculated CSV files for visualization stages
- Single source of truth for all mathematical operations
"""

import re
import glob
import json
import argparse
import pandas as pd
import numpy as np
from pathlib import Path
from logging_config import setup_logging

logger = setup_logging("process_metrics")

# ============================================================================
# CONFIGURATION: Physical Constants and Baseline Values
# ============================================================================

# Overridable via --results-dir/--output-dir (see main()) so isolated pilot/
# validation runs can target a separate directory (e.g. results/system_v2)
# without touching the documented-ground-truth results/system/ and
# results/processed_*.csv. Defaults are unchanged from the original pipeline.
RESULTS_SYS_DIR = "/home/yuvalk/MBMM/results/system"
OUTPUT_DIR = "/home/yuvalk/MBMM/results"
HARDWARE_METRICS_FILE = "/home/yuvalk/MBMM/results/hardware_metrics.json"

# Load hardware metrics (area, capacity) from extraction stage
HARDWARE_METRICS = {}
try:
    if Path(HARDWARE_METRICS_FILE).exists():
        with open(HARDWARE_METRICS_FILE, 'r') as f:
            HARDWARE_METRICS = json.load(f)
            logger.debug(f"Loaded hardware metrics for {len(HARDWARE_METRICS)} technologies")
except Exception as e:
    logger.warning(f"Could not load hardware metrics: {e}")

# Area Density Baseline (Hybrid-Empirical Approach)
DDR5_MM2_PER_GB = 35.0  # DDR5-4800 empirical baseline

# Clock frequencies for latency normalization (cycles → nanoseconds)
# DDR5-4800 transfers at 4800 MT/s on a DDR (double-data-rate) bus → 2400 MHz clock
# 2D/3D DRAM examples per their NVMain stats headers ("memory subsystem running
# at 666MHz" / "1333MHz"); all NVMain ReRAM and PCM configs run at 800 MHz
#
# T2.5 fix round 1: this table (and CPUFREQ_MHZ below) is now a FALLBACK
# only, used when a stats file's own clock-diagnostic line is absent (see
# extract_clocks_mhz/resolve_clocks_mhz). It is no longer the primary source
# of truth for any cycles-to-ns conversion: a technology can be simulated at
# more than one CLK (e.g. a ReRAM clock-sensitivity run at CLK 2400 still
# classifies as 1T1R_SLC by filename), and this table cannot know that --
# only the run's own stats file can.
CLOCK_FREQUENCY_MHZ = {
    'DDR5_4800':          2400,
    'DDR5_4800_64B':      2400,  # T2.4 cross-check: same CLK 2400 as the primary baseline
    '2D_DRAM_example':     666,
    '3D_DRAM_example':    1333,
    'pcm_microsoft_2009':  400,  # cycle-7 finding #9: CLK 800 was a stray override;
                                 # PCM's citable timing basis (and the fixed config) is 400MHz
    'PCM':                 400,  # T2.5 fix round 1: mirrors pcm_microsoft_2009 -- classify_technology()
                                 # can also return the generic 'PCM' key (any pcm-named file that
                                 # doesn't match the more specific pcm_microsoft_2009 pattern); without
                                 # this entry that case silently fell through to the 800 default.
    '1T1R_SLC':            800,
    '1T1R_MLC':            800,
    '1S1R_SLC':            800,
    '1S1R_MLC':            800,
    # T2.8: microsecond-silicon sensitivity configs mirror their SLC parent's
    # CLK (both still generated by 3_gen_nvmain_config.py at --freq 800, only
    # timing overridden) -- see resolve_clocks_mhz for why this is a fallback
    # only in practice (the stats file's own diagnostic line always wins).
    '1T1R_SILICON':        800,
    '1S1R_SILICON':        800,
}

# GLOBAL/CPUFreq clock domain (T2.5). NVMain's traceSim/traceMain.cpp sets
# `globalEventQueue->SetFrequency(config->GetEnergy("CPUFreq") * 1000000.0)`
# before the simulation loop (traceMain.cpp ~line 167), so every cycle
# GlobalEventQueue tracks -- including the "Exiting at cycle <n>" value it
# prints at trace exit/drain (traceMain.cpp ~line 305) -- is on the CPUFreq
# domain, NOT the model's own memory-clock (CLK) domain used by
# CLOCK_FREQUENCY_MHZ above. Every stats file's own diagnostic line confirms
# this directly, e.g. "NVMain: GlobalEventQueue: Added a memory subsystem
# running at 800MHz. My frequency is 3000MHz." -- "My frequency" there is
# GlobalEventQueue's own frequency, i.e. CPUFreq. global-constraints.md fixes
# CPUFreq at 3000 MHz for every model, so this is a single constant, not a
# per-technology table.
CPUFREQ_MHZ = 3000


# ============================================================================
# CLOCK RESOLUTION (T2.5 fix round 1)
# ============================================================================

def extract_clocks_mhz(content):
    """
    Parse NVMain's own per-run clock-domain diagnostic line, printed once per
    channel by src/EventQueue.cpp:472-473:

        NVMain: GlobalEventQueue: Added a memory subsystem running at
        <CLK>MHz. My frequency is <CPUFreq>MHz.

    <CLK> is the model's own memory-clock domain for THIS run (the same
    domain averageTotalLatency/averageEndToEndLatency/averageQueueLatency
    are reported in). <CPUFreq> is the GLOBAL event-queue domain the
    "Exiting at cycle <n>" line is printed in (see CPUFREQ_MHZ's comment
    above for the full source-code proof). Reading both from the file itself
    -- rather than from CLOCK_FREQUENCY_MHZ/CPUFREQ_MHZ, which only know a
    technology's *default* clock -- is what makes a clock-sensitivity run
    (e.g. a ReRAM config regenerated at CLK 2400 instead of the usual 800)
    convert cycles to ns correctly: the filename still classifies as
    1T1R_SLC either way, so a table keyed by technology name cannot tell the
    two runs apart, only the run's own stats file can.

    With more than one channel the line is printed once per channel; every
    occurrence must report the same (CLK, CPUFreq) pair -- a single run has
    exactly one CLK and one CPUFreq for the whole DIMM. If any two
    occurrences disagree, this raises ValueError rather than silently
    picking one (a malformed or concatenated stats file should be fixed, not
    guessed at).

    Returns (clk_mhz, cpufreq_mhz), both int. Returns (None, None) if the
    line is absent entirely (e.g. a hand-written test fixture, or a
    truncated/aborted-run file) -- callers must fall back to
    CLOCK_FREQUENCY_MHZ/CPUFREQ_MHZ in that case (see resolve_clocks_mhz,
    which does exactly that with a logged warning); this function itself
    never falls back silently.
    """
    matches = re.findall(
        r'running at\s+(\d+)MHz\.\s*My frequency is\s+(\d+)MHz', content)

    if not matches:
        return None, None

    clk_values = {int(m[0]) for m in matches}
    cpufreq_values = {int(m[1]) for m in matches}

    if len(clk_values) > 1 or len(cpufreq_values) > 1:
        raise ValueError(
            f"extract_clocks_mhz: disagreeing clock-diagnostic lines in the "
            f"same stats file -- CLK values found: {sorted(clk_values)}, "
            f"CPUFreq values found: {sorted(cpufreq_values)}. A single run "
            f"has exactly one CLK and one CPUFreq for the whole DIMM; this "
            f"looks like a malformed or concatenated stats file."
        )

    return clk_values.pop(), cpufreq_values.pop()


def resolve_clocks_mhz(content, technology, filename=""):
    """
    Resolve the (clk_mhz, cpufreq_mhz) pair to use for every cycles-to-ns
    conversion on this stats file, preferring the run's own recorded clocks
    (extract_clocks_mhz) over the CLOCK_FREQUENCY_MHZ/CPUFREQ_MHZ fallback.

    This is the single resolution point every cycles-to-time conversion in
    this file goes through (see calculate_latency_ns, extract_end_to_end_
    latency_ns, and parse_raw_stats' call site, which resolves once per file
    and reuses the result for Total/HW/Queue/E2E latency and for the
    delivered-bandwidth elapsed-time calculation).

    Falls back to CLOCK_FREQUENCY_MHZ[technology] (default 800, matching the
    table's own pre-T2.5 default) and CPUFREQ_MHZ only when the diagnostic
    line is absent entirely -- logged as a WARNING naming the file, since
    this should only happen for a hand-made or truncated stats file, never
    for a real NVMain run. When the line IS present and its CLK disagrees
    with the table's default for this technology, that is the expected,
    intended clock-sensitivity-run case (a technology simulated at a
    non-default CLK): logged at INFO, not a warning, and the file's own
    value always wins.
    """
    clk_mhz, cpufreq_mhz = extract_clocks_mhz(content)

    if clk_mhz is None:
        table_clk = CLOCK_FREQUENCY_MHZ.get(technology, 800)
        logger.warning(
            f"[CLOCK-FALLBACK] {filename}: no 'My frequency is' diagnostic "
            f"line found in this stats file; falling back to "
            f"CLOCK_FREQUENCY_MHZ[{technology}]={table_clk} MHz and "
            f"CPUFREQ_MHZ={CPUFREQ_MHZ} MHz. This should only happen for a "
            f"hand-made or truncated stats file, never a real NVMain run."
        )
        return table_clk, CPUFREQ_MHZ

    table_clk = CLOCK_FREQUENCY_MHZ.get(technology)
    if table_clk is not None and table_clk != clk_mhz:
        logger.info(
            f"[CLOCK-SENSITIVITY] {filename}: this run's own CLK "
            f"({clk_mhz} MHz) differs from CLOCK_FREQUENCY_MHZ[{technology}] "
            f"({table_clk} MHz) -- using the run's own value, as intended. "
            f"Expected for a clock-sensitivity config; unexpected otherwise."
        )

    return clk_mhz, cpufreq_mhz


# ============================================================================
# CLASSIFICATION FUNCTIONS
# ============================================================================

def classify_technology(filename):
    """Classify technology from filename using priority matching."""
    filename_lower = filename.lower()
    
    # Priority order: More specific patterns first. T2.4: the 64B cross-check
    # config is its own technology (DDR5_4800_64B), distinct from the primary
    # baseline (DDR5_4800, which both the legacy DDR5_4800_DRAM name and the
    # new DDR5_4800_DRAM_subchannel name classify to) -- its pattern must be
    # checked before the plain 'ddr5.*4800' pattern, which would otherwise
    # match it first (DDR5_4800_DRAM_64B contains 'ddr5...4800' too).
    patterns = [
        # T2.8: microsecond-silicon sensitivity configs (reram_micron16gb_1t1r_*,
        # reram_sandisk32gb_1s1r_*) contain '1t1r'/'1s1r' but never 'slc'/'mlc'/
        # 'selector', so the existing SLC/MLC patterns below would not actually
        # match them either way -- these are listed first regardless, so that
        # stays true even if a future SLC/MLC pattern is loosened.
        ('1T1R_SILICON', r'reram.*micron16gb.*1t1r'),
        ('1S1R_SILICON', r'reram.*sandisk32gb.*1s1r'),
        ('1T1R_MLC', r'reram.*1t1r.*mlc'),
        ('1T1R_SLC', r'reram.*1t1r.*slc(?!.*mlc)'),
        ('1S1R_MLC', r'reram.*selector.*mlc'),
        ('1S1R_SLC', r'reram.*selector.*slc(?!.*mlc)'),
        ('pcm_microsoft_2009', r'pcm_microsoft_2009'),
        ('PCM', r'pcm'),
        ('DDR5_4800_64B', r'ddr5.*4800.*64b'),
        ('DDR5_4800', r'ddr5.*4800'),
        ('3D_DRAM_example', r'3d_dram'),
        ('2D_DRAM_example', r'2d_dram'),
    ]
    
    for tech_name, pattern in patterns:
        if re.search(pattern, filename_lower):
            return tech_name
    
    logger.warning(f"Unknown technology in filename: {filename}")
    return None


def extract_architecture(filename):
    """Extract architecture scale from filename."""
    filename_lower = filename.lower()

    if 'full_dimm' in filename_lower:
        return 'full_dimm'
    elif '16chip' in filename_lower:
        return '16chip'
    elif '8chip' in filename_lower:
        return '8chip'
    elif 'single' in filename_lower:
        return 'single'

    # Default for DRAM/PCM (no architecture suffix). T2.4: both DDR5-4800
    # baseline variants (legacy, subchannel, 64B) are Architecture full_dimm
    # -- they are distinguished from each other by Technology instead (see
    # classify_technology), not by Architecture.
    if any(x in filename_lower for x in ['ddr5', '2d_dram', '3d_dram', 'pcm']):
        return 'full_dimm'

    logger.warning(f"Unknown architecture in filename: {filename}")
    return None


def extract_benchmark(filename):
    """Extract benchmark name from filename."""
    name = filename.replace('stats_', '').replace('.out', '')
    
    # Remove technology/architecture prefixes to isolate benchmark name.
    # T2.4: the two DDR5-4800 baseline variants' longer prefixes must be
    # checked before the plain 'DDR5_4800_DRAM_' prefix (a substring of
    # both), or only their 'subchannel_'/'64B_' tag gets stripped and it
    # ends up misread as part of the benchmark name.
    removal_patterns = [
        'DDR5_4800_DRAM_subchannel_',
        'DDR5_4800_DRAM_64B_',
        'DDR5_4800_DRAM_',
        '2D_DRAM_example_',
        '3D_DRAM_example_',
        'pcm_microsoft_2009_',
    ]
    
    for pattern in removal_patterns:
        if pattern in name:
            return name.replace(pattern, '', 1)
    
    # Handle ReRAM models (reram_22nm_[arch]_[mlc/slc]_[scale]_benchmark), and
    # T2.8's microsecond-silicon sensitivity configs (reram_micron16gb_1t1r_
    # full_dimm_benchmark / reram_sandisk32gb_1s1r_full_dimm_benchmark), which
    # also start with 'reram_' but not 'reram_22nm' -- both strip the same way
    # (find the architecture token, keep everything after it).
    if name.startswith('reram_'):
        for arch in ['full_dimm', '16chip', '8chip', 'single']:
            if arch in name:
                idx = name.find(arch + '_') + len(arch + '_')
                return name[idx:]
    
    return name


# ============================================================================
# METRIC EXTRACTION FUNCTIONS
# ============================================================================

def _extract_latency_stat(content, stat_name):
    """
    Extract a named NVMain latency statistic, averaging across all channels.

    NVMain emits one line per channel: channel0.FRFCFS.<stat_name> <value>
    DDR5-4800 has two sub-channels; single-channel ReRAM/PCM has one.
    Averaging gives a single representative number regardless of channel count.
    """
    pattern = rf'{re.escape(stat_name)}\s+([\d\.eE\-]+)'
    matches = re.findall(pattern, content, re.IGNORECASE)
    if not matches:
        return None
    try:
        values = [float(m) for m in matches]
        return sum(values) / len(values)
    except ValueError:
        return None


def extract_total_execution_cycles(content):
    """
    Extract averageTotalLatency (hardware latency + queue wait) from stats file.

    This is the correct end-to-end latency seen by a memory request.
    Previously the parser used a broad 'average.*latency' regex which matched
    averageLatency first (hardware-only, no queuing), losing the ISPV write-
    torture signal that lives in the queue component.
    """
    return _extract_latency_stat(content, 'averageTotalLatency')


def extract_hw_latency(content):
    """
    Extract averageLatency (pure hardware timing, no queue wait).

    Useful as a secondary column to decompose total latency into
    hardware vs queue components.
    """
    return _extract_latency_stat(content, 'averageLatency')


def extract_queue_latency(content):
    """
    Extract averageQueueLatency (time spent waiting in the FRFCFS queue).

    For write-heavy workloads (OFMAP), ISPV MLC writes back up the queue,
    causing a massive spike here relative to read-heavy (IFMAP) workloads.
    This is the primary empirical proof of the Write-Torture / ISPV penalty.
    """
    return _extract_latency_stat(content, 'averageQueueLatency')


def extract_end_to_end_latency_ns(content, clk_mhz):
    """
    Extract averageEndToEndLatency (NVMain T1.2 patch), combined across
    channels and converted to nanoseconds.

    NVMain emits one averageEndToEndLatency/measuredEndToEndLatencies pair
    per channel (per controller: channelN.FRFCFS or channelN.FRFCFS-WQF for
    PCM's write-queue controller), in the model's own memory-clock (CLK)
    cycle domain -- the same domain as averageTotalLatency, so it is
    comparable to Latency_ns/HW_Latency_ns/Queue_Latency_ns elsewhere in this
    file. With more than one channel (DDR5's two subchannels) the two
    channels rarely complete the same number of requests, so a plain mean
    across channels would over/under-weight whichever channel measured fewer
    end-to-end latencies; instead this combines the per-channel averages as a
    request-weighted mean, weighted by each channel's own
    measuredEndToEndLatencies count.

    `clk_mhz` must be the run's own memory-clock frequency (see
    resolve_clocks_mhz) -- T2.5 fix round 1: this used to take a `technology`
    string and look up CLOCK_FREQUENCY_MHZ internally, which silently used
    the table's default CLK for a technology even when the actual run used a
    different one (e.g. a clock-sensitivity config); callers now resolve the
    real clock once (per file, via resolve_clocks_mhz) and pass it in here.
    """
    lat_matches = re.findall(r'averageEndToEndLatency\s+([\d\.eE\-]+)', content)
    cnt_matches = re.findall(r'measuredEndToEndLatencies\s+(\d+)', content)

    if not lat_matches or not cnt_matches or len(lat_matches) != len(cnt_matches):
        return None

    try:
        lats = [float(m) for m in lat_matches]
        counts = [int(m) for m in cnt_matches]
    except ValueError:
        return None

    total_count = sum(counts)
    if total_count <= 0:
        return None

    weighted_cycles = sum(l * c for l, c in zip(lats, counts)) / total_count
    return calculate_latency_ns(weighted_cycles, clk_mhz)


def extract_completed_requests_and_bandwidth(content, cpufreq_mhz=CPUFREQ_MHZ):
    """
    Compute Completed_Requests and delivered bandwidth (MB/s) from NVMain's
    per-channel mem_reads/mem_writes counters and the elapsed simulated time.

    Completed_Requests = sum over channels of (mem_reads + mem_writes) --
    the same per-channel completed-request counts used for bandwidth, not
    NVMain's own totalReadRequests/totalWriteRequests (issued, not
    necessarily completed).

    Delivered_BW_MBps = (mem_reads + mem_writes) * 64 bytes / elapsed_time,
    summed over channels, in MB/s (1 MB = 1e6 bytes). This replaces NVMain's
    own bank-level `bandwidth` statistic, which is a per-bank instantaneous
    figure, not a DIMM-wide delivered-bandwidth number.

    Elapsed time comes from NVMain's own "Exiting at cycle <n>" line
    (traceSim/traceMain.cpp), printed once per run when the trace drains or
    the requested cycle budget is reached -- whichever happens first, so a
    trace that drains early correctly yields the (smaller) drain time, not
    the requested budget. That cycle count is in the GLOBAL/CPUFreq clock
    domain, NOT the model's own CLK domain used for E2E/queue/total latency
    elsewhere in this file.

    `cpufreq_mhz` defaults to CPUFREQ_MHZ (3000, global-constraints.md's
    fixed value) only for standalone/test callers that don't have a
    resolved value handy; T2.5 fix round 1: parse_raw_stats() always passes
    the run's own resolved CPUFreq explicitly (from resolve_clocks_mhz), so
    the default here is a fallback of last resort, not the normal path.

    Returns (completed_requests, delivered_bw_mbps), either element None if
    the stats file is missing the data needed (e.g. an aborted/incomplete
    run with no "Exiting at cycle" line).
    """
    reads = re.findall(r'\.mem_reads\s+(\d+)', content)
    writes = re.findall(r'\.mem_writes\s+(\d+)', content)
    exit_match = re.search(r'Exiting at cycle\s+(\d+)', content)

    if not reads or not writes or len(reads) != len(writes) or exit_match is None:
        return None, None

    try:
        read_counts = [int(m) for m in reads]
        write_counts = [int(m) for m in writes]
        elapsed_cycles = int(exit_match.group(1))
    except ValueError:
        return None, None

    if elapsed_cycles <= 0:
        return None, None

    elapsed_ns = elapsed_cycles * (1000.0 / cpufreq_mhz)
    elapsed_s = elapsed_ns * 1e-9

    completed_requests = sum(read_counts) + sum(write_counts)
    total_bytes = completed_requests * 64
    delivered_bw_mbps = (total_bytes / elapsed_s) / 1e6

    return completed_requests, delivered_bw_mbps


def extract_dimm_wear_stats(content):
    """
    Compute DIMM-wide wear-leveling summary stats from NVMain's per-subarray
    wear counters (T1.3 patch: wearLocations, wearTotalWrites, wearMaxWrites,
    one triple printed per subarray).

    Wear_Max_Writes = max(wearMaxWrites) over every subarray in the DIMM --
    the single hottest location anywhere in the module.
    Wear_HotSpot_Factor = that max, divided by the DIMM-wide mean writes per
    touched location (sum(wearTotalWrites) / sum(wearLocations)) -- i.e. how
    many times hotter the worst location is than the DIMM-wide average
    touched location.

    These stat lines are present (all reporting 0) even for a NullModel
    EnduranceModel (DDR5/PCM configs set `EnduranceModel NullModel`, which
    NVMain still registers stats for, but never populates: "Don't track data
    for NullModel"), and an all-read trace against a real (RowModel/
    WordModel) EnduranceModel produces the identical every-subarray-zero
    signature since no write ever happened. Both cases are handled the same
    way here: when no subarray recorded any write to any location
    (sum(wearLocations) <= 0) or every wearMaxWrites is 0, every DIMM-wide
    wear metric is None (blank in the CSV) -- never zero-filled, since a
    literal 0 would misleadingly read as "wear was measured and found to be
    zero" rather than "not measured for this technology/run".

    Never raises on partial/malformed input (T2.5 fix round 1): if
    wearLocations and wearMaxWrites are present but wearTotalWrites is
    absent entirely, or present but sums to 0, Wear_Max_Writes is still
    returned since it IS known -- only Wear_HotSpot_Factor (whose
    denominator depends on wearTotalWrites) comes back None. A malformed or
    partial wear block must blank the wear columns, not raise and lose the
    caller's entire row through parse_raw_stats' broad per-file
    `except Exception`.

    Returns (wear_max_writes, wear_hotspot_factor), either element None.
    """
    def _all_values(stat_name):
        pattern = rf'{re.escape(stat_name)}\s+([\d\.eE\-]+)'
        try:
            return [float(m) for m in re.findall(pattern, content)]
        except ValueError:
            return []

    locations = _all_values('wearLocations')
    total_writes = _all_values('wearTotalWrites')
    max_writes = _all_values('wearMaxWrites')

    if not locations or not max_writes:
        return None, None

    sum_locations = sum(locations)
    sum_total_writes = sum(total_writes)
    dimm_max_writes = max(max_writes)

    if sum_locations <= 0 or dimm_max_writes <= 0:
        return None, None

    if sum_total_writes <= 0:
        # wearTotalWrites missing entirely, or present but summing to 0:
        # Wear_Max_Writes is known (locations/max_writes are non-empty and
        # dimm_max_writes > 0, checked above), but the mean-per-touched-
        # location denominator is not -- blank only the hot-spot factor,
        # never divide by zero.
        return dimm_max_writes, None

    mean_writes_per_location = sum_total_writes / sum_locations
    dimm_hotspot_factor = dimm_max_writes / mean_writes_per_location

    return dimm_max_writes, dimm_hotspot_factor


def extract_total_power(content):
    """
    Extract total system power from a stats file: the sum of every rank's
    totalPower, across every channel.

    NVMain has no channel- or module-level totalPower aggregate of its own —
    only per-rank counters exist. A full DIMM keeps drawing background/leakage
    power on every rank whether or not that rank is doing work, so "total
    system power" must sum all ranks, not just the most-loaded one; picking a
    single rank silently discards the other (RANKS-1) ranks' contribution,
    understating the true total by a factor that tracks each technology's own
    rank x channel count (8x for full_dimm ReRAM, 4x for DDR5's 2 ranks x 2
    channels) — i.e. a different, incomparable discount per technology.
    Applied uniformly here, to every technology, for a like-for-like total.
    """
    # Pattern: "totalPower" followed by value and optional "W" unit
    pattern = r'totalpower\s+([\d\.eE\-]+)(?:\s*w)?'
    matches = re.findall(pattern, content, re.IGNORECASE)

    if not matches:
        return None

    # Filter for reasonable per-rank values (0.01W to 100W for memory systems)
    valid_powers = []
    for match_str in matches:
        try:
            power_val = float(match_str)
            if 0.01 <= power_val <= 100.0:
                valid_powers.append(power_val)
        except ValueError:
            continue

    if not valid_powers:
        return None

    return sum(valid_powers)


def extract_module_power_components(content):
    """
    Return the module-level (all ranks, all channels, summed) Watt-level power
    breakdown: backgroundPower, activatePower, burstPower, refreshPower.

    Sums the same per-rank totalPower entries extract_total_power() sums, so
    Static + Dynamic + Refresh reconciles to the Power column by construction
    (module-sum semantics, applied uniformly across every technology).
    Returns None if no rank block with a plausible totalPower (0.01-100W) is
    found in the file.
    """
    pattern = r'([\w.\-]+\.rank\d+)\.(totalPower|backgroundPower|activatePower|burstPower|refreshPower)\s+([\d\.eE\-\+]+)W'
    matches = re.findall(pattern, content)
    if not matches:
        return None

    ranks = {}
    for prefix, field, value_str in matches:
        try:
            ranks.setdefault(prefix, {})[field] = float(value_str)
        except ValueError:
            continue

    valid_ranks = {p: f for p, f in ranks.items()
                   if 'totalPower' in f and 0.01 <= f['totalPower'] <= 100.0}
    if not valid_ranks:
        return None

    totals = {'backgroundPower': 0.0, 'activatePower': 0.0,
              'burstPower': 0.0, 'refreshPower': 0.0}
    for fields in valid_ranks.values():
        for key in totals:
            totals[key] += fields.get(key, 0.0)

    return totals


RERAM_KEY_PREFIX = {
    '1T1R_SLC': 'reram_22nm_1t1r_slc',
    '1T1R_MLC': 'reram_22nm_1t1r_mlc',
    '1S1R_SLC': 'reram_22nm_selector_slc',
    '1S1R_MLC': 'reram_22nm_selector_mlc',
    # T2.8: silicon sensitivity is timing-only -- area, capacity, energies and
    # leakage stay NVSim's 22nm values from the same parent hardware-metrics
    # key 3_gen_nvmain_config.py's SILICON_TIMINGS table borrows them from, so
    # area/capacity lookups here mirror the SLC parent exactly.
    '1T1R_SILICON': 'reram_22nm_1t1r_slc',
    '1S1R_SILICON': 'reram_22nm_selector_slc',
}


def _reram_json_entry(technology_model):
    """Return the first matching hardware_metrics.json entry for a ReRAM tech."""
    if not HARDWARE_METRICS or technology_model not in RERAM_KEY_PREFIX:
        return None
    prefix = RERAM_KEY_PREFIX[technology_model]
    for key, entry in HARDWARE_METRICS.items():
        if key.startswith(prefix):
            return entry
    return None


def extract_area_mm2(content, technology_model):
    """
    Extract silicon area in mm² from hardware_metrics.json.
    DRAM/PCM use fixed ratios and return None here.
    """
    if technology_model in ['DDR5_4800', 'DDR5_4800_64B', 'pcm_microsoft_2009', '2D_DRAM_example', '3D_DRAM_example']:
        return None

    entry = _reram_json_entry(technology_model)
    if entry is None:
        logger.error(f"[CRITICAL] hardware_metrics.json lookup failed for {technology_model}")
        return None

    area = entry.get('area_mm2', None)
    if area is None or area <= 0:
        logger.error(f"[CRITICAL] Invalid area in hardware_metrics.json for {technology_model}: {area}")
        return None

    logger.debug(f"Found area for {technology_model}: {area} mm²")
    return area


def extract_physical_capacity_gb(technology_model):
    """
    Return per-chip physical capacity (GB) from hardware_metrics.json.

    NVMain stats report the *simulated system* address space, which varies with
    chip count and does not reflect the single-chip physical capacity needed for
    the area-density ratio.  This function always uses the JSON ground-truth.
    """
    if technology_model in ['DDR5_4800', 'DDR5_4800_64B', 'pcm_microsoft_2009', '2D_DRAM_example', '3D_DRAM_example']:
        return None

    entry = _reram_json_entry(technology_model)
    if entry is None:
        logger.error(f"[CRITICAL] hardware_metrics.json lookup failed for capacity of {technology_model}")
        return None

    cap = entry.get('capacity_gb', None)
    if cap is None or cap <= 0:
        logger.error(f"[CRITICAL] Invalid capacity in hardware_metrics.json for {technology_model}: {cap}")
        return None

    logger.debug(f"Found per-chip capacity for {technology_model}: {cap} GB")
    return cap


def extract_capacity_gb(content):
    """
    Extract capacity in GB from NVMain stats output.
    
    NVMain format: "defaultMemory.channel0.FRFCFS capacity is 65536 MB."
    Converts MB to GB automatically.
    """
    
    # Primary pattern: NVMain format "capacity is XXXXX MB"
    patterns = [
        (r'capacity\s+is\s+([\d\.]+)\s*MB', 'MB'),
        (r'capacity\s+is\s+([\d\.]+)\s*GB', 'GB'),
        (r'Capacity\s*:\s*([\d\.]+)(MB|GB|KB)', None),  # NVSim format
        (r'capacity\s*[:=]\s*([\d\.]+)\s*g?b', 'GB'),
    ]
    
    for pattern, unit in patterns:
        matches = re.findall(pattern, content, re.IGNORECASE)
        if matches:
            try:
                if unit is None:
                    # Handle (value, unit) tuple from second pattern
                    val, matched_unit = float(matches[0][0]), matches[0][1]
                    if matched_unit.upper() == 'MB':
                        return val / 1024.0
                    elif matched_unit.upper() == 'GB':
                        return val
                    elif matched_unit.upper() == 'KB':
                        return val / (1024.0**2)
                else:
                    val = float(matches[0])
                    if unit == 'MB':
                        return val / 1024.0
                    elif unit == 'GB':
                        return val
                    elif unit == 'KB':
                        return val / (1024.0**2)
            except (ValueError, IndexError, TypeError) as e:
                logger.debug(f"Error parsing capacity with pattern {pattern}: {e}")
                continue
    
    logger.error(f"[CRITICAL] Capacity extraction failed from stats file")
    return None


# ============================================================================
# CALCULATION FUNCTIONS
# ============================================================================

def decompose_power(record, technology, power):
    """
    Decompose total system power into static (leakage), dynamic (access), and
    refresh components using real, module-summed NVMain counters — no fixed
    per-technology ratios, and (as of the Priority-1 repair) no NonVolatile
    special-casing either.

    Single path for every technology: rank-level backgroundPower + activatePower
    + burstPower + refreshPower, summed across all ranks/channels by
    extract_module_power_components(), reconciles to totalPower by construction
    (both are sums over the same set of ranks). For ReRAM this now holds because
    Eactstdby/Eprestdby are derived per-technology from real NVSim leakage
    (see 3_gen_nvmain_config.py) instead of the previously-unused StandbyPower
    key — backgroundPower is a real, technology-differentiated NVMain counter
    now, not a generic default, so it no longer needs a separate residual-based
    path the way it did before that fix.

    Returns (dynamic, static, refresh, unattributed_power). unattributed_power
    is the leftover after Static+Dynamic+Refresh is subtracted from Power;
    should be ~0 (logged as a warning if it exceeds 3% of Power).
    """
    background = record.get('background_power')
    if background is None:
        logger.error(f"[CRITICAL] No rank-level power counters found for "
                    f"{technology} — cannot compute power split")
        return None, None, None, None

    static = background
    dynamic = (record.get('activate_power') or 0.0) + (record.get('burst_power') or 0.0)
    refresh = record.get('refresh_power') or 0.0
    unattributed = power - (static + dynamic + refresh)

    if power > 0 and abs(unattributed) > 0.03 * power:
        logger.warning(f"[POWER-RECONCILE] {technology}: components sum to "
                       f"{static + dynamic + refresh:.6f}W vs Power={power:.6f}W "
                       f"(unattributed {unattributed:.6f}W, {100 * unattributed / power:.1f}%)")

    return dynamic, static, refresh, unattributed


def calculate_pdp(latency_ns, power):
    """
    Calculate Power-Delay Product: Latency_ns × Total_System_Power (W·ns = nJ).

    Delay must be in nanoseconds, not cycles: each technology runs in its own
    clock domain (DDR5 2400 MHz vs ReRAM/PCM 800 MHz), so cycle-based PDP
    inflated higher-clocked technologies in cross-technology comparisons.
    """
    if latency_ns > 0 and power > 0:
        return latency_ns * power
    return 0.0


def calculate_latency_ns(cycles, clk_mhz):
    """
    Convert raw cycle count to nanoseconds using the given clock frequency.
    Formula: latency_ns = cycles * (1000 / clk_mhz)

    T2.5 fix round 1: `clk_mhz` must be the run's own memory-clock
    frequency, resolved once per file via resolve_clocks_mhz (preferring the
    stats file's own diagnostic line over CLOCK_FREQUENCY_MHZ's per-
    technology default) -- this used to take a `technology` string and look
    the frequency up in CLOCK_FREQUENCY_MHZ directly, which silently used
    the table's default CLK for a technology even when the actual run used a
    different one (a clock-sensitivity config, for example).
    """
    return cycles * (1000.0 / clk_mhz)


def calculate_area_density_ratio(area_mm2, capacity_gb, technology):
    """
    Calculate normalized area density ratio (Higher is Better).

    Formula: DDR5_baseline_mm2_per_GB / (tech_mm2_per_GB)
    DDR5 = 1.0.  Values > 1.0 are denser than DDR5; values < 1.0 are less dense.

    For ReRAM: extracted from hardware_metrics.json via hybrid-empirical method.
    For DRAM/PCM: fixed empirical ratios (inverted from the mm²/GB baseline).
    """

    # Fixed ratios expressed as density relative to DDR5 (higher = denser)
    # PCM 0.80 in the old mm²/GB system → inverted: 1/0.80 = 1.25
    fixed_ratios = {
        'DDR5_4800': 1.00,
        'DDR5_4800_64B': 1.00,  # T2.4: same physical DIMM/channel shape as the primary baseline
        'pcm_microsoft_2009': 1.25,
        '2D_DRAM_example': 1.053,
        '3D_DRAM_example': 1.176,
    }

    if technology in fixed_ratios:
        return fixed_ratios[technology]

    # For ReRAM: Require successful extraction (STRICT ERROR LOGGING)
    if area_mm2 is None or capacity_gb is None:
        logger.error(f"[CRITICAL] FAILED to extract area/capacity for {technology}. "
                    f"Area={area_mm2}, Capacity={capacity_gb}. Aborting calculation.")
        return None

    if capacity_gb <= 0:
        logger.error(f"[CRITICAL] Invalid capacity for {technology}: {capacity_gb} GB")
        return None

    if area_mm2 <= 0:
        logger.error(f"[CRITICAL] Invalid area for {technology}: {area_mm2} mm²")
        return None

    # Inverted: DDR5_baseline / tech → higher means denser than DDR5
    reram_mm2_per_gb = area_mm2 / capacity_gb
    ratio = DDR5_MM2_PER_GB / reram_mm2_per_gb

    logger.debug(f"{technology}: Area={area_mm2:.2f} mm², Capacity={capacity_gb:.2f} GB, "
                f"Density ratio = {DDR5_MM2_PER_GB}/({area_mm2:.2f}/{capacity_gb:.2f}) = {ratio:.4f}")

    return ratio


# ============================================================================
# PARSING AND AGGREGATION
# ============================================================================

def parse_raw_stats():
    """
    Parse all stats_*.out files and extract raw metrics.

    Returns (data, failures): `data` is the list of successfully-parsed
    records (unchanged shape from before T2.5 fix round 2); `failures` is a
    list of (filename, error_message) tuples for every file whose per-file
    parse raised an exception (e.g. extract_clocks_mhz's ValueError on
    disagreeing clock-diagnostic lines within one file).

    T2.5 fix round 2: this used to swallow such per-file exceptions
    completely -- logged at ERROR, the row silently dropped, no trace left
    in the return value, and the calling process still exited 0. The
    per-file try/except below is UNCHANGED in that one bad file still does
    not stop the rest of the files from parsing, but every failure is now
    collected and returned so the caller (main(), the CLI entry point) can
    decide whether that should be a fatal (non-zero exit) condition -- this
    library function itself never raises SystemExit or calls exit(); see
    main()'s --allow-parse-failures flag for the decision policy.

    The duplicate (Technology, Architecture, Benchmark) guard is NOT part of
    this failures list and is unchanged: it is a hard `raise ValueError`,
    deliberately not caught here, since a duplicate key would silently
    corrupt aggregates rather than just lose one row.
    """

    logger.info("="*80)
    logger.info("STAGE 6: DATA PROCESSING - Metric Extraction & Calculation")
    logger.info("="*80)
    logger.info(f"\nScanning for stats files in: {RESULTS_SYS_DIR}")

    stat_files = sorted(glob.glob(f"{RESULTS_SYS_DIR}/stats_*.out"))

    if not stat_files:
        logger.error(f"No stats files found in {RESULTS_SYS_DIR}")
        return [], []

    logger.info(f"Found {len(stat_files)} stats files\n")

    data = []
    failures = []
    # MLPerf excluded: all stats_*_mlperf_inference.out runs (2026-03-29) hit trace
    # EOF at cycle 0 with zero requests — mlperf_inference.nvt was missing/empty at
    # launch. Raw source survives at simulators/gem5/m5out/mlperf_raw.txt if we ever
    # regenerate the .nvt and re-run. See session audit 2026-07-06.
    excluded_benchmarks = ['mlperf_inference', 'mlperf']

    # T2.4: guard against two different stats files mapping to the same
    # (Technology, Architecture, Benchmark) key -- e.g. a legacy
    # stats_DDR5_4800_DRAM_*.out left over from an archive alongside a
    # freshly-generated stats_DDR5_4800_DRAM_subchannel_*.out for the same
    # benchmark: both classify to (DDR5_4800, full_dimm, <benchmark>).
    # Silently keeping one (or appending both as ambiguous duplicate rows)
    # would corrupt every downstream aggregate; fail loudly instead, naming
    # both files, so the results/ directory can be cleaned up deliberately.
    seen_keys = {}

    for filepath in stat_files:
        filename = Path(filepath).name

        # Classify
        tech = classify_technology(filename)
        if not tech:
            logger.debug(f"⊘ {filename}: Unknown technology, skipping")
            continue

        arch = extract_architecture(filename)
        if not arch:
            logger.debug(f"⊘ {filename}: Unknown architecture, skipping")
            continue

        bench = extract_benchmark(filename)
        if any(excl in bench for excl in excluded_benchmarks):
            logger.debug(f"⊘ {filename}: Excluded benchmark, skipping")
            continue

        key = (tech, arch, bench)
        if key in seen_keys:
            raise ValueError(
                f"Duplicate (Technology, Architecture, Benchmark) key {key}: "
                f"both {seen_keys[key]!r} and {filename!r} map to it. Remove or "
                f"rename one of the two stats files in {RESULTS_SYS_DIR} before "
                f"re-running process_metrics.py."
            )
        seen_keys[key] = filename

        # Parse file
        try:
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
            
            cycles = extract_total_execution_cycles(content)
            power = extract_total_power(content)

            if cycles is None or power is None or cycles <= 0 or power <= 0:
                logger.debug(f"⊘ {filename}: Missing or invalid metrics")
                continue

            hw_latency = extract_hw_latency(content)
            queue_latency = extract_queue_latency(content)

            # Extract area and per-chip physical capacity for ReRAM density ratio.
            # Both come from hardware_metrics.json so they are at the same scale.
            # extract_capacity_gb() reads the NVMain simulated address space which
            # scales with chip count and must NOT be used for the density formula.
            area_mm2 = extract_area_mm2(content, tech)
            capacity_gb = extract_physical_capacity_gb(tech)

            # Real, module-summed power-component counters (all ranks, all
            # channels) for the static/dynamic/refresh decomposition.
            module_power = extract_module_power_components(content)

            # T2.5 fix round 1: resolve this file's OWN clocks once (prefers
            # the stats file's own diagnostic line over the CLOCK_FREQUENCY_MHZ/
            # CPUFREQ_MHZ fallback -- see resolve_clocks_mhz), then reuse the
            # result for every cycles-to-ns conversion below and in
            # process_metrics() (Total/HW/Queue/E2E latency, delivered-bandwidth
            # elapsed time), instead of each conversion looking up a
            # technology-keyed table default independently.
            clk_mhz, cpufreq_mhz = resolve_clocks_mhz(content, tech, filename)

            # T2.5: end-to-end latency, delivered bandwidth, completed
            # requests, and DIMM-wide wear-leveling summary stats.
            e2e_latency_ns = extract_end_to_end_latency_ns(content, clk_mhz)
            completed_requests, delivered_bw_mbps = extract_completed_requests_and_bandwidth(
                content, cpufreq_mhz)
            wear_max_writes, wear_hotspot_factor = extract_dimm_wear_stats(content)

            data.append({
                'filename': filename,
                'technology': tech,
                'architecture': arch,
                'benchmark': bench,
                'total_execution_cycles': cycles,
                'hw_latency_cycles': hw_latency,
                'queue_latency_cycles': queue_latency,
                'power': power,
                'area_mm2': area_mm2,
                'capacity_gb': capacity_gb,
                'background_power': module_power['backgroundPower'] if module_power else None,
                'activate_power': module_power['activatePower'] if module_power else None,
                'burst_power': module_power['burstPower'] if module_power else None,
                'refresh_power': module_power['refreshPower'] if module_power else None,
                'clk_mhz': clk_mhz,
                'cpufreq_mhz': cpufreq_mhz,
                'e2e_latency_ns': e2e_latency_ns,
                'delivered_bw_mbps': delivered_bw_mbps,
                'completed_requests': completed_requests,
                'wear_max_writes': wear_max_writes,
                'wear_hotspot_factor': wear_hotspot_factor,
            })
            
            # T2.5 fix round 2: hw_latency/queue_latency can legitimately be
            # None (no averageLatency/averageQueueLatency line in a partial
            # or hand-made stats fixture) even when the row above parsed and
            # was appended successfully -- format them defensively instead
            # of crashing on None.__format__, which used to be silently
            # swallowed by the except block below (harmless before fix round
            # 2, since data.append() already ran) but would now be wrongly
            # counted as a parse FAILURE for a row that actually succeeded.
            hw_latency_str = f"{hw_latency:8.2f}" if hw_latency is not None else "     N/A"
            queue_latency_str = f"{queue_latency:8.2f}" if queue_latency is not None else "     N/A"

            if area_mm2 is not None and capacity_gb is not None:
                logger.debug(f"✓ {filename}: Tech={tech:15s} | Arch={arch:10s} | "
                            f"TotalCyc={cycles:10.2f} | HWCyc={hw_latency_str} | QCyc={queue_latency_str} | "
                            f"Power={power:10.4f}W | Area={area_mm2:.2f}mm² | Cap={capacity_gb:.2f}GB")
            else:
                logger.warning(f"⚠ {filename}: Tech={tech:15s} | Arch={arch:10s} | "
                              f"TotalCyc={cycles:10.2f} | HWCyc={hw_latency_str} | QCyc={queue_latency_str} | "
                              f"Power={power:10.4f}W | MISSING AREA/CAPACITY DATA")
        
        except Exception as e:
            logger.error(f"✗ {filename}: Failed to parse - {str(e)}")
            failures.append((filename, str(e)))
            continue

    logger.info(f"\nTotal data points extracted: {len(data)}\n")
    if failures:
        logger.error(f"{len(failures)} stats file(s) failed to parse and were skipped:")
        for fname, err in failures:
            logger.error(f"  - {fname}: {err}")
    return data, failures


def process_metrics(raw_data):
    """Calculate derived metrics from raw data."""
    
    logger.info("Calculating derived metrics...")
    
    processed = []
    
    for record in raw_data:
        tech = record['technology']
        power = record['power']
        cycles = record['total_execution_cycles']
        # T2.5 fix round 1: this run's OWN clock (resolve_clocks_mhz, resolved
        # once in parse_raw_stats), not a technology-keyed table lookup -- see
        # calculate_latency_ns's docstring for why that distinction matters.
        clk_mhz = record['clk_mhz']

        # Power decomposition (real NVMain counters, see decompose_power())
        dyn_power, stat_power, refresh_power, unattributed_power = decompose_power(record, tech, power)

        # Latency normalization: cycles → nanoseconds (clock-domain corrected)
        latency_ns = calculate_latency_ns(cycles, clk_mhz)
        hw_latency_ns = (calculate_latency_ns(record['hw_latency_cycles'], clk_mhz)
                         if record['hw_latency_cycles'] is not None else None)
        queue_latency_ns = (calculate_latency_ns(record['queue_latency_cycles'], clk_mhz)
                            if record['queue_latency_cycles'] is not None else None)

        # PDP in W·ns (queue-aware: latency_ns derives from averageTotalLatency)
        pdp = calculate_pdp(latency_ns, power)

        # Area density ratio (ReRAM hybrid-empirical)
        area_ratio = calculate_area_density_ratio(
            record['area_mm2'],
            record['capacity_gb'],
            tech
        )

        # If area extraction failed for ReRAM, use fallback but log it
        if area_ratio is None:
            if tech in ['1T1R_SLC', '1T1R_MLC', '1S1R_SLC', '1S1R_MLC',
                        '1T1R_SILICON', '1S1R_SILICON']:
                logger.error(f"[SKIP-WITH-FALLBACK] {tech}: Using 1.0 ratio due to extraction failure")
                area_ratio = 1.0
            else:
                area_ratio = 1.0  # Safe fallback for DRAM/PCM (shouldn't reach here)

        processed.append({
            'Technology': tech,
            'Architecture': record['architecture'],
            'Benchmark': record['benchmark'],
            'Total_Execution_Cycles': cycles,
            'HW_Latency_Cycles': record['hw_latency_cycles'],
            'Queue_Latency_Cycles': record['queue_latency_cycles'],
            'Latency_ns': latency_ns,
            'HW_Latency_ns': hw_latency_ns,
            'Queue_Latency_ns': queue_latency_ns,
            'Power': power,
            'Dynamic_Power': dyn_power,
            'Static_Power': stat_power,
            'Refresh_Power': refresh_power,
            'Unattributed_Power': unattributed_power,
            'PDP': pdp,
            'Area_Density_Ratio': area_ratio,
            'E2E_Latency_ns': record['e2e_latency_ns'],
            'Delivered_BW_MBps': record['delivered_bw_mbps'],
            'Wear_Max_Writes': record['wear_max_writes'],
            'Wear_HotSpot_Factor': record['wear_hotspot_factor'],
            'Completed_Requests': record['completed_requests'],
        })
    
    logger.info(f"Processed {len(processed)} data points\n")
    return processed


def calculate_geometric_mean_pdp(df_metrics):
    """Calculate geometric mean PDP per technology — full DIMM only."""

    logger.info("Calculating geometric mean PDP per technology (full_dimm only)...")

    # Filter to full_dimm for an apples-to-apples comparison.
    # DDR5 and PCM only have full_dimm records; including single/8chip/16chip
    # ReRAM configs would inflate their averages relative to the DRAM baselines.
    df_full_dimm = df_metrics[df_metrics['Architecture'] == 'full_dimm']

    geometric_means = {}

    for tech in df_full_dimm['Technology'].unique():
        tech_df = df_full_dimm[df_full_dimm['Technology'] == tech]
        edp_values = tech_df['PDP'].values

        if len(edp_values) > 0:
            # Geometric mean = exp(mean(ln(values)))
            geom_mean = np.exp(np.mean(np.log(edp_values)))
            geometric_means[tech] = geom_mean

            logger.debug(f"  {tech:20s}: {len(edp_values):2d} data points, "
                        f"Geometric Mean PDP = {geom_mean:12.2f}")

    logger.info(f"Calculated geometric means for {len(geometric_means)} technologies\n")
    return geometric_means


# ============================================================================
# OUTPUT FUNCTIONS
# ============================================================================

def save_bar_chart_metrics(df_processed):
    """Save metrics for bar chart visualization."""
    
    output_file = Path(OUTPUT_DIR) / "processed_bar_chart_metrics.csv"
    output_dir = output_file.parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Select columns for bar charts (includes latency decomposition for write-torture analysis).
    # T2.5: E2E_Latency_ns, Delivered_BW_MBps, Wear_Max_Writes, Wear_HotSpot_Factor,
    # Completed_Requests are appended at the end (existing columns/order unchanged)
    # so downstream visualize_*.py scripts that index by name keep working.
    df_output = df_processed[[
        'Technology', 'Architecture', 'Benchmark',
        'Total_Execution_Cycles', 'HW_Latency_Cycles', 'Queue_Latency_Cycles',
        'Latency_ns', 'HW_Latency_ns', 'Queue_Latency_ns',
        'Power', 'Dynamic_Power', 'Static_Power', 'Refresh_Power', 'Unattributed_Power', 'PDP',
        'E2E_Latency_ns', 'Delivered_BW_MBps', 'Wear_Max_Writes', 'Wear_HotSpot_Factor',
        'Completed_Requests'
    ]]

    df_output.to_csv(output_file, index=False)

    logger.info(f"✓ Saved bar chart metrics: {output_file}")
    logger.debug(f"  Records: {len(df_output)}, Benchmarks: {df_output['Benchmark'].nunique()}")


def save_pareto_metrics(df_processed):
    """Save metrics for Pareto frontier visualization."""
    
    output_file = Path(OUTPUT_DIR) / "processed_pareto_metrics.csv"
    output_dir = output_file.parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Select columns for Pareto plots (all architectures)
    df_output = df_processed[[
        'Technology', 'Architecture', 'Benchmark',
        'Total_Execution_Cycles', 'Latency_ns', 'Power'
    ]]
    
    df_output.to_csv(output_file, index=False)
    
    logger.info(f"✓ Saved Pareto metrics: {output_file}")
    logger.debug(f"  Records: {len(df_output)}, Architectures: {df_output['Architecture'].nunique()}")


def save_hero_metrics(df_processed):
    """Save metrics for hero graph visualization."""
    
    output_file = Path(OUTPUT_DIR) / "processed_hero_metrics.csv"
    output_dir = output_file.parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Select columns for hero graphs (include write-torture decomposition + area density).
    # T2.5: same five new columns as save_bar_chart_metrics, appended at the end.
    df_output = df_processed[[
        'Technology', 'Benchmark',
        'Total_Execution_Cycles', 'HW_Latency_Cycles', 'Queue_Latency_Cycles',
        'Power', 'PDP', 'Area_Density_Ratio',
        'E2E_Latency_ns', 'Delivered_BW_MBps', 'Wear_Max_Writes', 'Wear_HotSpot_Factor',
        'Completed_Requests'
    ]]
    
    df_output.to_csv(output_file, index=False)
    
    logger.info(f"✓ Saved hero metrics: {output_file}")
    logger.debug(f"  Records: {len(df_output)}, Technologies: {df_output['Technology'].nunique()}")


def save_geometric_means(geometric_means_dict):
    """Save pre-calculated geometric mean PDP values."""
    
    output_file = Path(OUTPUT_DIR) / "processed_geometric_means.csv"
    output_dir = output_file.parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    df_output = pd.DataFrame(
        list(geometric_means_dict.items()),
        columns=['Technology', 'Geometric_Mean_PDP']
    )
    
    df_output.to_csv(output_file, index=False)
    
    logger.info(f"✓ Saved geometric means: {output_file}")


# ============================================================================
# MAIN PIPELINE
# ============================================================================

def main():
    """Execute data processing pipeline."""

    global RESULTS_SYS_DIR, OUTPUT_DIR

    parser = argparse.ArgumentParser(description="MBMM Step 6: Metrics Processing")
    parser.add_argument("--results-dir", default=RESULTS_SYS_DIR,
                        help="Directory to scan for stats_*.out files (default: results/system).")
    parser.add_argument("--output-dir", default=OUTPUT_DIR,
                        help="Directory to write processed_*.csv files (default: results/).")
    parser.add_argument("--allow-parse-failures", action="store_true",
                        help="T2.5 fix round 2: downgrade per-file stats-parse failures from "
                             "a fatal condition (ERROR logged, process exits 1) to a WARNING "
                             "(process exits 0). The rows that DID parse are always written to "
                             "the CSVs regardless of this flag -- one bad file never hides the "
                             "others; this flag only controls the exit code, for knowingly "
                             "processing an old/partial dataset that has files this version "
                             "can't parse.")
    args = parser.parse_args()
    RESULTS_SYS_DIR = args.results_dir
    OUTPUT_DIR = args.output_dir

    try:
        # Step 1: Parse raw stats files
        raw_data, parse_failures = parse_raw_stats()

        if parse_failures:
            log_fn = logger.warning if args.allow_parse_failures else logger.error
            log_fn(f"{len(parse_failures)} stats file(s) failed to parse and were skipped "
                   f"(see per-file errors above):")
            for fname, err in parse_failures:
                log_fn(f"  - {fname}: {err}")
            if args.allow_parse_failures:
                logger.warning("--allow-parse-failures set: continuing with exit 0 despite "
                                "the failure(s) above.")
            else:
                logger.error("Failing (exit 1) because of the parse failure(s) above. Pass "
                              "--allow-parse-failures to continue with a WARNING instead, once "
                              "these are understood/expected (e.g. an old dataset this version "
                              "can't fully parse).")

        if not raw_data:
            logger.error("No data extracted from stats files")
            return False

        # Step 2: Convert to DataFrame for processing
        df_processed = pd.DataFrame(process_metrics(raw_data))
        
        # Step 3: Calculate geometric means
        geometric_means = calculate_geometric_mean_pdp(df_processed)
        
        # Step 4: Output intermediate CSV files
        logger.info("Saving intermediate metric files...")
        
        save_bar_chart_metrics(df_processed)
        save_pareto_metrics(df_processed)
        save_hero_metrics(df_processed)
        save_geometric_means(geometric_means)
        
        logger.info("="*80)
        logger.info("✅ DATA PROCESSING COMPLETE")
        logger.info("="*80)
        logger.info("\nGenerated intermediate metric files:")
        logger.info("  - processed_bar_chart_metrics.csv")
        logger.info("  - processed_pareto_metrics.csv")
        logger.info("  - processed_hero_metrics.csv")
        logger.info("  - processed_geometric_means.csv")
        logger.info("\nReady for visualization stage.\n")

        # T2.5 fix round 2: the CSVs above are always written from whatever
        # DID parse (one bad file never hides the others), but the process
        # still exits non-zero on unallowed parse failures -- decided here,
        # in the CLI entry point, not inside the library function
        # parse_raw_stats() itself.
        if parse_failures and not args.allow_parse_failures:
            return False

        return True

    except Exception as e:
        logger.error(f"Pipeline failed: {str(e)}", exc_info=True)
        return False


if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)
